# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e12e00d6e5544f2ff0d7a20785040674bbea57fda282d6b4c1a6a44e29c4b60ed438fcf0d8aeb1bbf271d5d7a4dd2c5a8d39771c210790dabeb6983770349520
  aws_access_key_id: AKIAIV2ZCUPVPPL4D4VA
  aws_secret_access_key: 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

test:
  secret_key_base: a3d16995c36522660aaa75568006f06656b5fc226752ad7cd4db41879642bd91f1e1a056c9eefc0a29e48d4a6d062593eb447a0ce330b0056bd5dd89f415bf9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: AKIAIV2ZCUPVPPL4D4VA
  aws_secret_access_key: 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
